In [1]:
import numpy as np

In [42]:
a=np.random.randint(1,10,(1,6))
b=np.random.randint(1,10,(3,6))
c=np.random.randint(1,10,(2,6))
d=np.random.randint(1,10,6)

In [32]:
a+b

array([[ 8, 10,  5,  9, 12, 10],
       [ 3, 10,  6, 10, 12, 13],
       [ 8,  6,  9, 10, 10, 13]])

In [33]:
a

array([[1, 5, 2, 3, 3, 7]])

In [34]:
b

array([[7, 5, 3, 6, 9, 3],
       [2, 5, 4, 7, 9, 6],
       [7, 1, 7, 7, 7, 6]])

In [13]:
# 2 RULES

In [15]:
# SHAPE SHOULD BE SAME , START FROM CHECKING FROM RIGHT

In [16]:
# IF IT HAS 1 IN IT THAN IT WILL WORK

In [43]:
a+c

array([[17, 14, 14, 15,  7, 17],
       [14, 15, 11, 14,  9, 14]])

In [44]:
c+d

array([[16, 12, 12,  9,  8, 13],
       [13, 13,  9,  8, 10, 10]])